# Any generated resources should go into these directories
out_dir: "{{ playbook_dir }}/out"
host_out_dir: "{{ out_dir }}/{{ ansible_host }}"
ca_base_resources_dir: "{{ out_dir }}/ca"

# Repositories
hyperkube_image_repo: "gcr.io/google-containers/hyperkube"
kubernetes_version: "v1.12.0"

# Newly downloaded binaries will be installed in this directory
binary_copy_path: "/opt/bin"
docker_compose_path: "/opt/bin/docker-compose"
docker_path: "/usr/bin"
base_kube_dir: "/etc/kubernetes"

# Config files
kube_config_dir: "{{ base_kube_dir }}/configs"

# Resources manifest-files
manifest_dir: "{{ base_kube_dir }}/manifests"
compose_manifest_dir: "{{ manifest_dir }}/compose"
kube_manifest_dir: "{{ manifest_dir }}/kube"

kube_pki_dir: "{{ base_kube_dir }}/pki"

# Systemd service files location
systemd_service_dir: "/etc/systemd/system"
kube_psp_dir: "{{ kube_addons_dir }}/pod-security-policies"

# Local node-port where HAProxy is running
# as reverse-proxy to the apiserver
haproxy_port: 6443
# The port on master-node where APIServer is running
apiserver_port: 443

dns_service_ip: "10.3.0.10"
dns_domain: "cluster.local"
service_ip_range: "10.3.0.0/24"
kube_service_network : "10.3.0.1"
kube_pod_network: "10.2.0.0/16"
# APIServer used for initiating setup.
# Initially, we need a static apiserver address.
# This static address is replaced by a HAProxy reverse-proxy
# once the addons are setup as required.
first_master_host: "{{ groups['kubernetes-masters'][0] }}"
init_apiserver_address: |
  "https://{{ hostvars[first_master_host]['ansible_env']['COREOS_PUBLIC_IPV4'] }}:{{ apiserver_port }}"
