all:
  vars:
    ansible_python_interpreter: /opt/bin/python

  children:

    etcd:
      hosts:
        etcd-01:
          ansible_ssh_private_key_file: ./.vagrant/machines/etcd-01/virtualbox/private_key

    kubernetes:
      children:

        kubernetes-masters:
          hosts:
            kube-master-01:
              ansible_ssh_private_key_file: ./.vagrant/machines/kube-master-01/virtualbox/private_key

        kubernetes-workers:
          hosts:
            kube-worker-01:
              ansible_ssh_private_key_file: ./.vagrant/machines/kube-worker-01/virtualbox/private_key
            kube-worker-02:
              ansible_ssh_private_key_file: ./.vagrant/machines/kube-worker-02/virtualbox/private_key
