---
# tasks file for roles

- name: Create ca directory
  file:
    path: "{{ ca_base_resources_dir }}"
    state: directory

- name: Create CA root key
  command: openssl genrsa
            -out ca-key.pem 2048
  args:
    chdir: "{{ ca_base_resources_dir }}"
    # creates: ca-key.pem

- name: Create CA root certificate
  command: openssl req -x509
            -new  -nodes
            -key  ca-key.pem
            -days 10000
            -out  ca.pem
            -subj "/CN=kube-ca"
  args:
    chdir: "{{ ca_base_resources_dir }}"
    # creates: ca.pem

- name: Create cluster administrator key
  command: openssl genrsa
            -out admin-key.pem 2048
  args:
    chdir: "{{ ca_base_resources_dir }}"
    # creates: admin-key.pem

- name: Create cluster administrator csr
  command: openssl req -new
            -key  admin-key.pem
            -out  admin.csr
            -subj "/CN=kube-admin/O=system:masters"
  args:
    chdir: "{{ ca_base_resources_dir }}"
    # creates: admin.csr

- name: Create cluster administrator certificate
  command: openssl x509 -req
            -in admin.csr
            -CA ca.pem
            -CAkey ca-key.pem
            -CAcreateserial
            -out admin.pem
            -days 365
  args:
    chdir: "{{ ca_base_resources_dir }}"
    # creates: admin.pem
