ansible_templates_dir: "{{ role_path }}/templates"
kube_addons_dir: "{{ base_kube_dir }}/addons"

# For CoreDNS
image_arch: "{{host_architecture | default('amd64')}}"
coredns_image_repo: "gcr.io/google-containers/coredns"
coredns_version: "{%- if image_arch != 'amd64' -%}1.1.3{%- else -%}1.2.2{%- endif -%}"
coredns_image_tag: "{{ coredns_version }}{%- if image_arch != 'amd64' -%}__{{ image_arch}}_linux{%- endif -%}"

coredns_replicas: 1
coredns_ordinal_suffix: -primary

dns_memory_limit: 170Mi
dns_cpu_requests: 100m
dns_memory_requests: 70Mi
