# tasks file for roles
---

- name: Recursively copy templates
  include: "{{ playbook_dir }}/macros/recursive_template_copy.yml"
  with_items:
    # Configs
    - name: Add Kubernetes configs
      src : "{{ ansible_templates_dir }}/configs"
      dest: "{{ kube_config_dir }}"

- name: Non-recursively copy templates
  include: "{{ playbook_dir }}/macros/template_copy.yml"
  with_items:
    # Docker-Compose manifests
    - name: Add Docker-Compose manifests
      src : "{{ ansible_templates_dir }}/manifests/docker-compose"
      dest: "{{ compose_manifest_dir }}"
    # Kubernetes Manifests
    - name: Add Kubernetes manifests
      src : "{{ ansible_templates_dir }}/manifests/kubernetes"
      dest: "{{ kube_manifest_dir }}"
    # Systemd Services
    - name: Add component service-files
      src : "{{ ansible_templates_dir }}/services"
      dest: "/etc/systemd/system"

- name: Start Kubelet
  systemd:
    name: kubelet
    state: started
    enabled: true
    daemon_reload: yes

- name: Wait for apiserver to start
  wait_for:
    host: "127.0.0.1"
    port: "8080"
    delay: "5"
    connect_timeout: "2"
    timeout: "1800" #For initial Docker-Image downloads/setups
